### ISSUE TITLE
YAML support

### ISSUE THREAD

**Issue by gbersac** [rust-lang/rustc-serialize#100]
Yaml is a very popular and I am sure a lot of rustacean will use it. There is already one library implementing it, but, even though it is probably very efficient, it is a c wrapper and it would be great to have one library taking care of the serialization for all the most popular languages.

Since [json is a subset of yaml](http://www.yaml.org/spec/1.2/spec.html#id2759572), there could even be an interface for both, making it easy to translate from one to another. [Xml could be added as I explained in another issue](https://github.com/rust-lang/rustc-serialize/issues/45).

```rust
let data1 = xml::from_string(xml_string); // return a Node structure
let data2 = yaml::from_string(yaml_string); // also return a Node structure
let data3 = json.from_string(json_string); // also return a Node structure
```

Tell me if you are interested in implementing that feature, that's a topic I am eager to work on.

**Comment by alexcrichton** [comment]
This would be awesome! I suspect it would not be a part of this library, however, but rather done as an external crate.

**Comment by gbersac** [comment]
I am not interested in making another library. I prefer upgrading a great library than creating a mediocre on my own.

If I create a yaml parser which is an equivalent of your json parser, would you consider merging it ? Since I am not an expert, I'll probably need some help.

**Comment by alexcrichton** [comment]
Right now we're not looking to expand this library too much as we hope to deprecated it one day (fingers crossed!). With crates.io and Rust traits, however, it's super easy to make a high-quality library externally, and it also keeps the compile times down for everyone using `rustc-serialize` who doesn't require YAML encoding/decoding. An example of a library like this is [toml](https://crates.io/crates/toml)
