### ISSUE TITLE
Floats do not roundtrip correctly

### ISSUE THREAD

**Issue by jamii** [rust-lang/rustc-serialize#113]
``` rust    
let string = format!("{}", Json::F64(0.107));
let json = Json::from_str(&string).unwrap();
let float = json.as_f64().unwrap();
println!("{:?}", 0.107);
println!("{}", float);
assert_eq!(float, 0.107);
```

Other implementations eg in v8 get this right. The default rust printer also gets it right.

**Comment by alexcrichton** [comment]
Running this on nightly gives:

```
0.107
0.10700000000000001
```

**Comment by alexcrichton** [comment]
Er oops, commented too soon, running this on nightly gives:

```
0.107
0.10700000000000001
thread '<main>' panicked at 'assertion failed: `(left == right)` (left: `0.10700000000000001`, right: `0.107`)', src/main.rs:13
```

Which is to say that these are indeed different (the floating point printing routines were recently greatly improved) but it appears the parsing code is just a little off.

**Comment by jamii** [comment]
Looks like the std library has the same behaviour - http://is.gd/H6W6oe

**Comment by jamii** [comment]
It's kinda weird that the compiler doesn't appear to be using the same float parser.

**Comment by jamii** [comment]
Dupe of https://github.com/rust-lang/rust/issues/7648
