### ISSUE TITLE
Using obsolete "for Sized?" syntax

### ISSUE THREAD

**Issue by chills42** [rust-lang/rustc-serialize#18]
After an update to the latest nightly I have compilation issues

rustc --version
rustc 1.0.0-nightly (ea6f65c5f 2015-01-06 19:47:08 +0000)

cargo build
   Compiling rustc-serialize v0.2.5
/Users/craig.hills/.cargo/registry/src/github.com-1ecc6299db9ec823/rustc-serialize-0.2.5/src/serialize.rs:193:25: 193:30 error: obsolete syntax: for Sized?
/Users/craig.hills/.cargo/registry/src/github.com-1ecc6299db9ec823/rustc-serialize-0.2.5/src/serialize.rs:193 pub trait Encodable for Sized? {
                                                                                                                                      ^~~~~
note: no longer required. Traits (and their `Self` type) do not have the `Sized` bound by default
/Users/craig.hills/.cargo/registry/src/github.com-1ecc6299db9ec823/rustc-serialize-0.2.5/src/serialize.rs:399:17: 399:18 error: obsolete syntax: `Sized? T` syntax for removing the `Sized` bound
/Users/craig.hills/.cargo/registry/src/github.com-1ecc6299db9ec823/rustc-serialize-0.2.5/src/serialize.rs:399 impl<'a, Sized? T: Encodable> Encodable for &'a T {
                                                                                                                              ^
note: write `T: ?Sized` instead
/Users/craig.hills/.cargo/registry/src/github.com-1ecc6299db9ec823/rustc-serialize-0.2.5/src/serialize.rs:405:13: 405:14 error: obsolete syntax: `Sized? T` syntax for removing the `Sized` bound
/Users/craig.hills/.cargo/registry/src/github.com-1ecc6299db9ec823/rustc-serialize-0.2.5/src/serialize.rs:405 impl<Sized? T: Encodable> Encodable for Box<T> {
                                                                                                                          ^
/Users/craig.hills/.cargo/registry/src/github.com-1ecc6299db9ec823/rustc-serialize-0.2.5/src/base64.rs:73:24: 73:29 error: obsolete syntax: for Sized?
/Users/craig.hills/.cargo/registry/src/github.com-1ecc6299db9ec823/rustc-serialize-0.2.5/src/base64.rs:73 pub trait ToBase64 for Sized? {
                                                                                                                                 ^~~~~
note: no longer required. Traits (and their `Self` type) do not have the `Sized` bound by default
/Users/craig.hills/.cargo/registry/src/github.com-1ecc6299db9ec823/rustc-serialize-0.2.5/src/base64.rs:173:26: 173:31 error: obsolete syntax: for Sized?
/Users/craig.hills/.cargo/registry/src/github.com-1ecc6299db9ec823/rustc-serialize-0.2.5/src/base64.rs:173 pub trait FromBase64 for Sized? {
                                                                                                                                    ^~~~~
/Users/craig.hills/.cargo/registry/src/github.com-1ecc6299db9ec823/rustc-serialize-0.2.5/src/hex.rs:21:21: 21:26 error: obsolete syntax: for Sized?
/Users/craig.hills/.cargo/registry/src/github.com-1ecc6299db9ec823/rustc-serialize-0.2.5/src/hex.rs:21 pub trait ToHex for Sized? {
                                                                                                                           ^~~~~
note: no longer required. Traits (and their `Self` type) do not have the `Sized` bound by default
/Users/craig.hills/.cargo/registry/src/github.com-1ecc6299db9ec823/rustc-serialize-0.2.5/src/hex.rs:57:23: 57:28 error: obsolete syntax: for Sized?
/Users/craig.hills/.cargo/registry/src/github.com-1ecc6299db9ec823/rustc-serialize-0.2.5/src/hex.rs:57 pub trait FromHex for Sized? {
                                                                                                                             ^~~~~
/Users/craig.hills/.cargo/registry/src/github.com-1ecc6299db9ec823/rustc-serialize-0.2.5/src/json.rs:2305:22: 2305:27 error: obsolete syntax: for Sized?
/Users/craig.hills/.cargo/registry/src/github.com-1ecc6299db9ec823/rustc-serialize-0.2.5/src/json.rs:2305 pub trait ToJson for Sized? {
                                                                                                                               ^~~~~
note: no longer required. Traits (and their `Self` type) do not have the `Sized` bound by default
error: aborting due to 8 previous errors
Could not compile `rustc-serialize`.

**Comment by TyOverby** [comment]
Should this issue be closed now?

**Comment by alexcrichton** [comment]
Aha, yes!
