### ISSUE TITLE
TreeMap instead of BTreeMap in docs?

### ISSUE THREAD

**Issue by toqueteos** [rust-lang/rustc-serialize#24]
> ...
> ```Object: equivalent to rust's Treemap<String, json::Json>```
> ...

https://github.com/rust-lang/rustc-serialize/blob/f9f4ba83fb0f98b2bb974317397db1f578d51be2/src/json.rs#L32

Is this a typo or a change related to consistent renaming of the std collections in a near future?

**Comment by alexcrichton** [comment]
Ah this is a typo, it should be `BTreeMap`, thanks for finding!
