### ISSUE TITLE
Cap'n Proto support?

### ISSUE THREAD

**Issue by caizixian** [rust-lang/rustc-serialize#35]

**Comment by BurntSushi** [comment]
You probably want this: https://github.com/dwrensha/capnproto-rust

**Comment by caizixian** [comment]
@BurntSushi Maybe you can add some of the code to this repo.

**Comment by BurntSushi** [comment]
From looking at the repo, it doesn't appear to support Rust's decoding/encoding infrastructure.

There's really no reason to absorb it here. The `capnproto-rust` repo can support encoding/decoding on its own.
