### ISSUE TITLE
Using RustcEncodable and RustcDecodable for stdlib types?

### ISSUE THREAD

**Issue by Hoverbear** [rust-lang/rustc-serialize#37]
I was hoping to use this crate to `#[derive(RustcEncodable, RustcDecodable)]` on `SocketAddr`, however it does not appear to be possible with the orphan trait restrictions.

Are there any guides on how I might do this?

**Comment by BurntSushi** [comment]
Yup, orphan trait restrictions prevent you from doing this. So I think you have two options:

1. Lobby to have this package include impls for `SocketAddr`.
2. Define a newtype around `SocketAddr` and impl decoding/encoding on that newtype. For example (not compiler checked):

```rust
struct MySocketAddr(SocketAddr);

impl Decodable for MySocketAddr {
    fn decode<D: Decoder>(d: &mut D) -> Result<MySocketAddr, D::Error> {
        let s = try!(d.read_str());
        MySocketAddr(/* create SocketAddr from `s` */)
    }
}
```

This comes with its downsides though. If `v` has type `MySocketAddr`, then you have to use `v.0` when passing it to functions that expect a `SocketAddr`.

**Comment by Hoverbear** [comment]
Thanks, that answers my questions!
