### ISSUE TITLE
rustc-serialize breaks build on CI

### ISSUE THREAD

**Issue by hawkw** [rust-lang/rustc-serialize#41]
I'm working on a project which requires `rustc-serialize` as a dependency (for `docopt`). The project builds fine on my machine, but a few commits ago, the build on Travis CI started [failing](https://travis-ci.org/hawkw/seax/builds/48273533) due to an error when compiling `rustc-serialize`. The build has [failed](https://travis-ci.org/hawkw/seax/builds/48366457) ever since.

I'm pretty new to Rust, so it's entirely possible that I've done something wrong, but I haven't been able to find any changes between the last [successful build](https://travis-ci.org/hawkw/seax/builds/47551239) and the [first failed build](https://travis-ci.org/hawkw/seax/builds/48273533) that would break `rustc-serialize`. 

Any ideas?

**Comment by BurntSushi** [comment]
Is [this](https://github.com/hawkw/seax) your repo? If so, you should run `cargo update` and commit the changes to `Cargo.lock`. Currently, your `Cargo.lock` forces your program to build with `rustc-serialize` `0.2.8`, but `0.2.9` is the latest.

**Comment by hawkw** [comment]
Yeah, that [fixes the build](https://travis-ci.org/hawkw/seax/builds/48415692). Thanks.
