### ISSUE TITLE
Hyphen in "rustc-serialize" isn't sound

### ISSUE THREAD

**Issue by bestouff** [rust-lang/rustc-serialize#53]
Veeery minor quibble, but putting a "-" in the name makes things uselessly complicated. Is it too late to change the name to, e.g. rustc_serialize ou just rustserialize ?

**Comment by alexcrichton** [comment]
I think that this may be more effective to weigh in on [this discussion](http://internals.rust-lang.org/t/pre-rfc-resolve-support-for-hyphens-in-crate-names/1459/20) as this relates to the broader question and can be affected by the outcome of that decision. Thanks for the issue though!
