### ISSUE TITLE
"There is no old_path in std" error

### ISSUE THREAD

**Issue by mfirry** [rust-lang/rustc-serialize#54]
Why do I get this error?

```unresolved import `std::old_path`. There is no `old_path` in `std````

**Comment by BurntSushi** [comment]
Without knowing what version of `rustc` you're using, it's impossible to explain why.

My guess is that you're using an old version of `rustc` that predates the existence of `std::old_path`. I'd recommend updating to the latest nightly (which is what this repo tracks).

(`std::old_path` is a temporary crate to reduce churn in the transition to the new `os`/`io`/`path` crates in `std`.)

**Comment by mfirry** [comment]
rustc 1.0.0-nightly (458a6a2f6 2015-01-25 21:20:37 +0000)

**Comment by BurntSushi** [comment]
Yes, you should update.
