### ISSUE TITLE
Implement RustcDecodable and RustcEncodable for arrays.

### ISSUE THREAD

**Issue by alexchandel** [rust-lang/rustc-serialize#55]
Specifically some short fixed-length arrays like `[T;1]` through `[T;16]`. There are like a dozen tuple implementations, so this wouldn't be much of a stretch.

**Comment by james-darkfox** [comment]
You might want to parse to a `Vec<T>`; then handle that directly.

**Comment by alexchandel** [comment]
Ideally I'd like to avoid the cost of allocating and pushing to a vector, and I'd like to serialize a struct with an array member.

**Comment by james-darkfox** [comment]
IIRC; you've already allocated for the parser before it even handles your types.

**Comment by alexchandel** [comment]
And yet, using a Vec<T> instead of a [T; n] introduces additional allocation into my types and code. It also deletes the type safety I had in using fixed-length arrays, instead forcing me to manually check the length of a vector. That is not the right design.

**Comment by james-darkfox** [comment]
Tuples were manually handled as with macros; IIRC, there is some work (at least on the TODO for rust) to enable having traits against numeric types. A concept whose name I can't recall right now - but will allow us to implement over all lengths of any T, and work with numbers in the types.. Ex. `fn f<T>(a: [T; n], b: [T; m]) -> [T; n+m] {...}`
