### ISSUE TITLE
Package on crates.io broken

### ISSUE THREAD

**Issue by Potpourri** [rust-lang/rustc-serialize#89]
```
 Downloading rustc-serialize v0.3.8

Unable to get packages from source

Caused by:

  Failed to unpack package `rustc-serialize v0.3.8`

Caused by:

  corrupt deflate stream
```

**Comment by jmitchell** [comment]
I'm also bumping into this.

May be coming from Cargo's Flate2 dependency: https://github.com/alexcrichton/flate2-rs/blob/931360fb2bba4656aa944f1a1e91d1ee1c5a5033/src/raw.rs#L239

Here's where Cargo uses Flate2 to unpack the package: https://github.com/rust-lang/cargo/blob/964e72ffc0ae29d6ff1fa1d23a6141f8152433d1/src/cargo/sources/registry.rs#L354

**Comment by jmitchell** [comment]
I don't have enough context to know what may have changed with the interpretation, production, or handling of the streams.

**Comment by msiemens** [comment]
Using `tar` to unzip `rustc-serialize-0.3.8.crate` also fails:

```
$ tar -xvf rustc-serialize-0.3.8.crate
rustc-serialize-0.3.8/.gitignore
rustc-serialize-0.3.8/.travis.yml
rustc-serialize-0.3.8/Cargo.toml
rustc-serialize-0.3.8/LICENSE-APACHE
rustc-serialize-0.3.8/LICENSE-MIT
rustc-serialize-0.3.8/README.md
rustc-serialize-0.3.8/src/base64.rs
rustc-serialize-0.3.8/src/collection_impls.rs
rustc-serialize-0.3.8/src/hex.rs
rustc-serialize-0.3.8/src/json.rs

gzip: stdin: unexpected end of file
tar: Unexpected EOF in archive
tar: Unexpected EOF in archive
tar: Error is not recoverable: exiting now
```

Looks like the package got corrupted while uploading or something...

**Comment by Hoverbear** [comment]
Confirming the newest `rustc-serialize` is broken on crates.io.

```
➜  raft git:(master) cargo test --verbose
Unable to get packages from source

Caused by:
  Failed to unpack package `rustc-serialize v0.3.8`

Caused by:
  corrupt deflate stream
```

**Comment by jmitchell** [comment]
@huonw, I'm guessing you packaged and deployed the crate after bumping the version a few hours ago.

Do you still have the *.crate file that got deployed? Can its contents be extracted?

**Comment by huonw** [comment]
Hm, I don't think it was me, maybe @alexcrichton?

**Comment by jmitchell** [comment]
Err, right. Apparently I haven't had enough coffee... :coffee:

**Comment by dirvine** [comment]
Yes, this seems to be causing widespread failure across many crates now.

**Comment by nstoddard** [comment]
This is preventing me from starting a new project :(

**Comment by andersk** [comment]
Workaround for users running into this problem: edit the `Cargo.lock` file to change all `rustc-serialize` references from `0.3.8` to `0.3.7`, then rerun `cargo build`.

**Comment by eminence** [comment]
or set `rustc-serialize = "=0.3.7"` in Cargo.toml

**Comment by dirvine** [comment]
@eminence I think that will only work of nothing you include also includes `rustc-serialize` Many crates have that dependency also.

**Comment by bdero** [comment]
Running into this as well.

@dirvine - I think changing all of the `rustc-serialize` version references in `Cargo.lock` should work (as it did for me), since lock files track *all* dependencies, including dependencies of dependencies.

**Comment by brson** [comment]
I also hit this!

**Comment by bdero** [comment]
@dirvine Whoops, I think I may have missed the context there in my last comment. Sorry.

**Comment by alexcrichton** [comment]
I've yanked 0.3.8 and republished as 0.3.9, sorry for the inconvenience everyone!
