### ISSUE TITLE
invalid character `-` in crate name

### ISSUE THREAD

**Issue by yohanesu** [rust-lang/rustc-serialize#91]
Getting this error with newest rust

error: invalid character `-` in crate name: `rustc-serialize`
error: aborting due to previous error
Build failed, waiting for other jobs to finish...
Could not compile `rustc-serialize`.

**Comment by alexcrichton** [comment]
Thanks for the report! This looks like you may just need to update Cargo, however, and then everything should be ok!

**Comment by yohanesu** [comment]
I did update and that's why it broke. According to RFC 940 hyphen in crate names are no longer allowed so don't you have to update the Cargo.toml?

**Comment by alexcrichton** [comment]
The details of RFC 940 mean that *crate names* cannot contain hyphens, but *package names* still may contain hyphens.

**Comment by yohanesu** [comment]
I am having problem with rust-lang/num which has rustc-serialize as a dependency. It would not build with most recent version of rust so what I did was fork num and rustc-serialize, change - to _ in rustc-serialize and change num's Cargo.toml so that the rustc-serialize dependency point to my fork. If rustc-serialize is not the problem then what is your suggestion for a solution?

**Comment by alexcrichton** [comment]
What are the precise versions of `rustc` and `cargo` that you are using?

**Comment by yohanesu** [comment]
[mirama@JMBA-DEV wlcairo]$ rustc --version
rustc 1.0.0-dev (d8be84eb4 2015-03-29) (built 2015-03-30)
[mirama@JMBA-DEV wlcairo]$ cargo --version
cargo 0.0.1-pre-nightly (a58ffd7 2015-02-27) (built 2015-02-27)

cargo seems old... but cargo is included in rust-lang/rust right? i assumed it would be updated when i do git pull and rebuild rust from source.

**Comment by yohanesu** [comment]
Oh I see now.. It is not.. I am using cargo from old binary installation... Sorry for the trouble. I will install new one and see how it goes..

**Comment by yohanesu** [comment]
Ok problem solved! Thanks for the help and sorry again...

**Comment by alexcrichton** [comment]
No problem! Glad it worked out :)
