### ISSUE TITLE
Minor documentation issue

### ISSUE THREAD

**Issue by GarethLewin** [rust-lang/rustc-serialize#96]
I would create a PR but I am not sure what the actual correct value is:

Here there is a 'i' in the format string https://github.com/rust-lang/rustc-serialize/blob/master/src/json.rs#L133

Here it says there should be a 'j' https://github.com/rust-lang/rustc-serialize/blob/master/src/json.rs#L153

**Comment by alexcrichton** [comment]
Thanks!
