### ISSUE TITLE
Decodable for struct with reserved words as keys

### ISSUE THREAD

**Issue by octplane** [rust-lang/rustc-serialize#97]
Hi,

I'm trying to deser a json blob with a `ref` field. And guess what, `ref` is a reserved word. Is there any way to overcome this "limitation" or do I have to write down my decodable implementation for this struct ?

Thank you very much!

**Comment by alexcrichton** [comment]
Unfortunately for now you'll have to write a custom `Decodable` and `Encodable` implementation as the `#[derive]` modes do not have any configuration.

**Comment by alexcrichton** [comment]
Ah and for the future we hope to explore better options for doing this in libraries like [serde](http://github.com/erickt/rust-serde)!
